server:
  host: "0.0.0.0" 
  port: "4000"
  httpport: "8080"

database:
  host: "mysql.railway.internal"
  port: "3306"
  user: "root"
  password: "hJRbNsFArVSEWqHvIpjPXAQGMipWGGcn"
  name: "railway"